### PR TITLE
modified import statements for more readablity and memory enhancement

### PR DESCRIPTION
**Pull request by amiensa**
changed the ' `import subprocess` '  => ' `from subprocess import check_output` '

### CODE REVIEW

**Comment by FrancescoCaracciolo** [comment]
@amiensa have you finished or is this a draft?

**Comment by amiensa** [comment]
> @amiensa have you finished or is this a draft?

I finished, I just wanted to do something. I know my edits were kinda nothing :') .

**Comment by FrancescoCaracciolo** [comment]
Even small contributions are appreciated. I was asking because you made an extra commit after opening the PR and maybe you wanted to do something else

**Comment by amiensa** [comment]
> Even small contributions are appreciated. I was asking because you made an extra commit after opening the PR and maybe you wanted to do something else

Ah thankyouuu . It's just my first use of git, so I may have sent it mistakenly

**Comment by qwersyk** [comment]
Thank you very much for your contribution to our project, even the smallest help makes the project better.

**Pull request merged**
